service: electrical-quiz-lambda # only alphanumeric chars and hyphens allowed

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128 # set the max memory of the Lambdas in MB
  timeout: 10 # the timeout is 10 seconds (default is 6)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-east-1

functions:
  # /questions
  getAllQuestions:
    handler: handler.getAllQuestions
    events:
      - http:
          path: questions
          method: get
          cors: true
  getOneQuestion:
    handler: handler.getOneQuestion
    events:
      - http:
          path: questions/{id}
          method: get
          cors: true
  createQuestion:
    handler: handler.createQuestion # point to exported create function in handler.js
    events:
      - http:
          path: questions
          method: post
          cors: true
  updateQuestion:
    handler: handler.updateQuestion
    events:
     - http:
          path: questions/{id}
          method: put
          cors: true
  deleteQuestion:
    handler: handler.deleteQuestion
    events:
     - http:
          path: questions/{id}
          method: delete
          cors: true

  # /quiz
  getQuiz:
    handler: handler.getQuiz
    events:
      - http:
          path: quiz
          method: get
          cors: true
  checkQuiz:
    handler: handler.checkQuiz
    events:
      - http:
          path: quiz
          method: post
          cors: true
plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation

